# Generated by Django 4.2.6 on 2024-03-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
